/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ywwi3c7dbbhtzdymerbbevmlue.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5jf4yp6owfbmjevauonsyoypry",
    "aws_cognito_identity_pool_id": "us-east-1:837c32b8-b846-40fb-8495-7846e190a30c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Accna4y6r",
    "aws_user_pools_web_client_id": "16estpi406le1516ahjeb1s2to",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "PHONE_NUMBER",
        "NAME",
        "EMAIL",
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "findvegan-image-storage232132-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
